### ISSUE TITLE
; should serve as a delimiter between commands

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#32]
Currently in the case of `echo "hello ; echo "goodbye" ` the output is hello ; echo goodbye on minishell where the same command outputs hello\ngoodbye\n. It appears that ; behaves as a delimiter between commands.

**Comment by nwhean** [comment]
The instruction says that the shell should
> Not interpret unclosed quotes or unspecified special characters like \ or ;.

This is to say, currently, `;` character is treated like a normal text, instead of interpreted as a new command delimiter.
