### ISSUE TITLE
Whitespace is should not be trimmed before saving into history

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#33]
Current implementation trims whitespace before writing into the history file. Therefore, if a subsequent similar command is input with space, it is saved as a duplicate. For example `history` followed by `history ` followed by another `history ` will save 3 entries of history without whitespace. In bash, whitespace is not trimmed before saving into history as can be seen when scrolling up the previous history with up arrow.

**Comment by nwhean** [comment]
Resolved in commit a522318b15a875801ad97a17d747c437bc248a96.
