### ISSUE TITLE
value in the key=value pair needs to be trimmed of whitespace before saving to env.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#34]
In the current implementation, `export TEST='<4 spaces>TEST<4 spaces>'` followed by `echo $TEST` prints `<4 spaces>TEST<4 spaces>` whereas in bash, it just prints `TEST`. In bash however,  running `export TEST='|         TEST         |'` followed by `echo $TEST` prints `| TEST |`.

**Comment by nwhean** [comment]
Resolved in commit 3ba46c849ecb5b93f8bcb5d5734b568c617d0b9f. Whitespace is trimmed before quote removal in the parser.
