### ISSUE TITLE
'>' redirection followed by pipe saves the wrong input.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#35]
In the current implementation, the command `cat << go > test | cat << stop` saves the input from the second cat command into the test file rather than saving the input from the first cat command. Alternatively, having two files `test1` and `test2`, running `cat test1 > test3 | cat test2` saves the contents from test2 into test3.

**Comment by nwhean** [comment]
`cat test1 > test3 | cat test2` is actually interpreted like this: `(cat test1 > test3) | (cat test2)`. That is to say, *test3* will have the content of *test1*, then content of *test2* will be printed out on screen. As of commit 13b73f26b2158ab7ee716cecaa807d8b2ac2906b, this behaviour is correct. However, multiple heredoc in different simple commands are not carried out correctly yet.

**Comment by nwhean** [comment]
`cat << go > test | cat << stop` is working correctly as of commit 7e866edbc9c91d691e1e2ae94c1c00108f00ce2d.
