### ISSUE TITLE
'>>' redirection followed by piping appends the wrong input to file.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#36]
Similar to issue #35, In the current implementation, the command cat << go >> test | cat << stop appends the input from the second cat command into the test file rather than saving the input from the first cat command. Alternatively, having two files test1 and test2, running cat test1 >> test3 | cat test2 appends the contents from test2 into test3.

**Comment by nwhean** [comment]
Resolved in commit 7e866edbc9c91d691e1e2ae94c1c00108f00ce2d.
