### ISSUE TITLE
exit ' <number>' should set $? to <number> instead of setting $? to 2.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#47]
Based on bash testing, exit followed by only numbers(with however many spaces before or after the number) within quotations set $? to the number within the quotations. For example exit '      50' or exit '50    ' sets $? to 50.

Should also print exit before printing error message based on bash behaviour.

**Comment by nwhean** [comment]
What you've describe is already the existing behaviour, is it not?

**Comment by nwhean** [comment]
Reason why I don't want to print *exit* from exit built-in function is because exit, when run in a pipeline, will print the exit messasge also, which is not the same behaviour as bash. Zsh actually does not print the exit message upon exit.

**Comment by davidwkw** [comment]
For this issue, current implementation of minishell raises an error and sets the exit code to 2 instead of the number within single quotes whereas bash is exits normally and set the exit code to the given number if it's just a number + space.

**Comment by nwhean** [comment]
Resolved in commit 3c2b28dd61db74c3e2c4b7c80f00625e644aaefe.
