### ISSUE TITLE
exit -<number> sets $? to the value of the last 8 bits of number?

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#48]
https://code.woboq.org/userspace/glibc/bits/waitstatus.h.html#_M/__WEXITSTATUS for reference.

**Comment by nwhean** [comment]
It'll be between 0 to 255. You can see in this line:
https://github.com/nwhean/42_core_minishell/blob/e6c825d2e5d7d139f6951b700af0fcb8678a071a/builtin_exit.c#L68
that the number is limit to that range.
