### ISSUE TITLE
export KEY='<double quotes>' does not append \ behind double quotes before saving into the environment.

### ISSUE THREAD

**Issue by davidwkw** [nwhean/42_core_minishell#50]
In current the current implementation of minishell, export KEY='"' or export KEY='""' does not escape the double quotes within the external single quotes before saving into environment unlike bash which escapes all double quotes within external single quotes before saving into env. i.e export KEY='"' results in KEY="\"" when export is ran.

**Comment by davidwkw** [comment]
It appears that single quotes are converted to double quotes when saving into the environment, thus the need to escape double quotes. Single quotes within double quotes does not seem to experience the same issues.

**Comment by nwhean** [comment]
Since we are not interpreting `\` as a special character, i.e the escape character, we don't have to implement this in minishell.
